<footer id="site-footer" class="site-footer">
  <div class="site-container">
    <div class="col col-1">
      <address>
        <a href="https://www.google.com/maps/place/Leadership+Square/@35.4693815,-97.5192653,17z/data=!3m1!4b1!4m2!3m1!1s0x87b2172eddb389a5:0x8a7758a0f362ff2e">Two Leadership Square <br/>
          211 North Robinson Avenue <br/>
          Suite 450 <br/>
          Oklahoma City, OK 73102</a>
      </address>
    </div>
    <div class="col col-2">
      <a href="tel:4056063350">(405) 606-3350</a> <br/>
      <a href="mailto:info@trmg.com">email us</a>
    </div>
    <div class="col col-3">
      ©2015 Tomlinson, Rust, McKinstry & Grable P.C. All Rights Reserved <br/>
      <a href="disclaimer.php">Disclaimer</a>
    </div>
  </div>
</footer>